### ISSUE TITLE
Doesn't support configurable world

### ISSUE THREAD

**Issue by ChimpGamer** [BentoBoxWorld/Level#115]
#### Describe the bug

When loading the Level addon this error appears. I changed bskyblock_world to skyblock_world in the bskyblock config
ERROR [BentoBox] [Level] TopTen world bskyblock_world is not known on server.

#### Steps to reproduce the behavior

Change the world-name of BSkyBlock for example to something else then default.

#### Expected behavior

I expected it to respect the BSkyBlock configuration setting.

##### BentoBox Version (Mandatory)

```
Running PAPER Invalid.
BentoBox version: 1.9.2
Database: JSON
Loaded Game Worlds:
skyblock_world (SkyBlock): Overworld, Nether, End
Loaded Addons:
BSkyBlock 1.9.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
IslandFly 1.7.0 (ENABLED)
Level 1.9.0 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
What happened here is that you had some Level data that was associated with the old name still in the database. i.e., the database was not deleted when you changed the name of the world. So when Level loaded, it sees the old data and reports that there is no longer a world called **bskyblock_world** anymore. Which is correct because you changed the name to **skyblock_world**. 

You can ignore the error if you like, or look through your **BentoBox/database/LevelData** folder when the server is stopped and delete files that refer to the old name. Or if you are still setting up your server, just delete the whole folder.
