### ISSUE TITLE
Weird Bug for some players

### ISSUE THREAD

**Issue by Bigdude601** [BentoBoxWorld/Level#126]
Describe the bug
when one player uses the /island level command it throws a null exception but not other players

To Reproduce
I have no idea whats causing this bug.

Expected behavior
It would normally calculate the island level. It works fine for all other players.

Screenshots
https://i.imgur.com/qJuUl7u.png

Server Information (please complete the following information):

    Database being used: Flat file
    OS: Linux
    Java Version: open jdk 11
    Other plugins? All other plugins have been removed 1 by 1 in a testing environment and the issue still persists.

**Comment by tastybento** [comment]
can you do `bbox version` in the console and copy and paste everything because that'll tell me what versions of everything you are running.

**Comment by Bigdude601** [comment]
https://i.imgur.com/nJ5DxtF.png

**Comment by tastybento** [comment]
It looks like somehow these players have a null value for their level data. I'm not sure how that happened. Anyway, have a go with the latest build 345 as I've added some code that should remove those elements -https://ci.codemc.io/job/BentoBoxWorld/job/Level/345/
Also, I recommending upgrade BentoBox to 1.11.0 because it fixes a bug that may have caused this in the first place.

**Comment by tastybento** [comment]
Let me know if you still see the error with the latest build.

**Comment by Bigdude601** [comment]
After updating it is now working. Thanks for the help!
