### ISSUE TITLE
The ability to see in-game details of /is level

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Level#143]
#### Is your feature request related to a problem?

To be able to see all the detail information about your island block limit (like a in console wirting).

#### Describe the solution you'd like us to implement.

Maybe make GUI or with pages in chat.

### Additional context

This example what should players see about their island with command.
[message (6).txt](https://github.com/BentoBoxWorld/BSkyBlock/files/4452435/message.6.txt)

**Comment by tastybento** [comment]
https://discordapp.com/channels/272499714048524288/393756208990912523/726453265713332264

**Comment by tastybento** [comment]
**Skipzy Idea**
Like this for the main page, top heads are the 1st to 12th, with the remainder at the bottom being "yours", thus no need for players to utilise the FB for the level.

![image](https://user-images.githubusercontent.com/4407265/85932186-add48e80-b87e-11ea-84e7-116ec8d96da5.png)

GUI Name:
```
- '&8&lTop Islands'
Head Info:
- '&dIsland &5%bskyblock_island_name% &7(#%Level_bskyblock_top_value_#RANK#%)'
- ' '
- '&5&l* &d&lIsland Level &7%Level_bskyblock_island_level%'
Line below is optional, this will hook into Shopgui+ and calculate the cash worth, of said island.
- '&5&l* &d&lIsland Worth &7$%Level_bskyblock_island_worth_formatted%'
- ' '
- '&5&l* &d&lMembers:'
The placeholder below, should display the names vertically, as opposed to the normal layout with commas. However, if there are no members, instead it will output &cNone
- '  &f&l- %bskyblock_island_members_list%'
- ' '
- '&f&oLeft-Click &7&oto view their collection.'
The next one is optional, this is to determine if it should say visit, if user has placed said island warp sign.
- '&f&oRight-Click &7&oto visit their island.'
```

Then with the sub GUI, it'd look cool if you laid it out like this [Image below], everything apart from the Spawner_Cage, and the book and quill should be interchangeable, so that users can change what is the most valuable.

```
GUI Name:
- '&8%bskyblock_island_name%'
Spawner Cage:
- '&d&lSpawners ->'
Book & Quill:
- '&d&lItems ->'
Each Block: Example...
- '&7Cobblestone'
- '&5&l* &d&lQuantity &fx%amount%'
```
![image](https://user-images.githubusercontent.com/4407265/85932181-a1e8cc80-b87e-11ea-8a33-b4cab67015f4.png)

**Comment by tastybento** [comment]
This is largely done in 2.3.0. I'm sure there will be improvements, but the island block report is now done there.
