### ISSUE TITLE
Extreme stuttering caused by consecutive block placement.

### ISSUE THREAD

**Issue by NolanMC** [BentoBoxWorld/Level#191]
#### Describe the bug

(This may need to be transferred to an addon, I have not pinpointed a specific cause yet.)
If you place blocks consecutively, block placing starts to stutter extremely.
#### Steps to reproduce the behavior

1. Within an Island, place blocks in a straight line while flying for best results.
2. Block Placement will then stutter and some blocks will no longer place, when they should without interference.
#### Expected behavior

Block placement should not stutter if the user is authorized to place a block within the island. 
#### Screenshots and videos (Optional)

Here is a video with reproducible steps: 
https://www.youtube.com/watch?v=8kPGYrynneE

I am using a vanilla client and simply holding right click down to place blocks while flying.
### Environment
This is currently occurring on both Paper 1.16.3 build 196 and Tuinity build 154
##### Output of `/bbox version` (Mandatory)

```
[14:52:25 INFO]: Running Invalid (TUINITY) 1.16.3.
[14:52:25 INFO]: BentoBox version: 1.15.1-SNAPSHOT-b1875
[14:52:25 INFO]: Database: SQLITE
[14:52:25 INFO]: Loaded Game Worlds:
[14:52:25 INFO]: bskyblock_world (bskyblock): Overworld, [nether_color]Nether, [end_color]End
[14:52:25 INFO]: Loaded Addons:
[14:52:25 INFO]: Biomes 1.13.0 (ENABLED)
[14:52:25 INFO]: Border 1.0.9 (ENABLED)
[14:52:25 INFO]: BSkyBlock 1.14.1-SNAPSHOT-b673 (ENABLED)
[14:52:25 INFO]: IslandFly ${version}${build.number} (ENABLED)
[14:52:25 INFO]: Level 2.5.0-SNAPSHOT-b418 (ENABLED)
[14:52:25 INFO]: Warps 1.10.1-SNAPSHOT-b268 (ENABLED)
_______
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

There was a recent CraftBukkit/Spigot update which changed the behavior of PlayerInteractEvent. Not sure if that is relevant here.

**Comment by tastybento** [comment]
This is not anything to do with Levels. What you saw looks like lag to me and it's just a coincidence that you changed the addon. There isn't anything in the Levels addon that handles PlayerInteractEvent or block placement. Levels only does something when you run the Levels command. 

I don't think this is related to BentoBox at all. When you place blocks over a void, we've had reports of the server having to run a lot of lighting calculations that ultimately go nowhere. By placing them so fast in creative modem your server is probably choking on them.

I'm sorry, but there's nothing actionable here. If you manage to grab some timings or logs that show otherwise, feel free to open an issue again.
