### ISSUE TITLE
Nether / end level calculation

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/Level#205]
## EN ##

Hello,

#### Is your feature request related to a problem?
Can you calculate the island level when the player come for the first time on her nether or end island.

#### Describe the solution you'd like us to implement.
When the player join her nether or end island the island value is automatically calculate withe the end / nether island.
But by default the island level ils calculate with the overworld island

#### Describe alternatives you've considered.
Or you can make a permission for has the end / nether count in the is value

## FR ##

Bonjour,

Pouvez-vous ajouter une feature qui permettrait de calculer l'is level de l'end et du nether uniquement quand il à accès à cette île, donc quand il join son île pour la première fois.

Si ce n'est pas possible pourquoi pas faire une permission qui permettrait d'ajouter l'is value du nether / de l'end à l'is level total, et par défaut laisser uniquement le calcul du monde overworld

Thank you very much,

I think this is a great feature
(sory for my bad english)

**Comment by tastybento** [comment]
I think this already exists. If you select the option to include the nether or end in the config.yml, then the island level will be zeroed at the start:

```
# Include nether island in level calculations.
# Warning: Enabling this mid-game will give players with an island a jump in
# island level. New islands will be correctly zeroed.
nether: true <--- Set this to true
# 
# Include end island in level calculations.
# Warning: Enabling this mid-game will give players with an island a jump in
# island level. New islands will be correctly zeroed.
end: false <- set this to true
```

However, be careful about the Nether Ceiling - I recommend you turn it off because when chunks are generated it will give the player a higher level for no effort, just exploring. Alternatively, make Netherrack and glowstone a limited count.

Does this do what you want?

**Comment by Teyir** [comment]
Ok,

Thank you very much
