### ISSUE TITLE
possibilities to refresh island levels automatically

### ISSUE THREAD

**Issue by Tobahodimu** [BentoBoxWorld/Level#219]
Hello! I happen to be using your bSkyblock plugin. I would like my players' island levels to refresh automatically, but I can't figure out how I could do it from the "Level" addons settings.

I don't know if it's already possible or if it's being implemented but it would be excellent.

Hope to receive a positive response from you! Wishing you a good day or a good evening!

Thanks for reading!

**Comment by tastybento** [comment]
You can have levels calculate when the player logs in by setting this option to true:
https://github.com/BentoBoxWorld/Level/blob/e0736fca4c8dbf79b4a7cd39293bfde335baac38/src/main/resources/config.yml#L29

It is not possible to run the level calculations continuously because they are exceptionally processor intensive as every block on the island has to be checked, but at least running them on login will enable islands to be update without the player having to run the level command manually.
