### ISSUE TITLE
Negative Island Levels

### ISSUE THREAD

**Issue by CubBossa** [BentoBoxWorld/Level#225]
#### Describe the bug
I setup my server to have 4 worlds: skyblock_spawn, skyblock_islands and both nether and end for skyblock_islands. skyblock_spawn was setup to be the main world in the server.properties. I changed this due to a portal problem. I had nether and end disabled in server.properties and bukkit.yml to prevent skyblock_spawn from generating its unused dimensions.
So i changed skyblock_islands to be my main world and re-enabled nether and end, which "broke" the world generators. I just had to open the bukkit.yml and add generator: BentoBox for all island worlds. I noticed some days later that some chunks generated with flat world / vanilla nether and end. I had to delete them manually and this is what caused the actual issue. Islands that were created at a position where and while the according nether was still vanilla, they would have a huge island level. But this was zeroed out as i was told in discord. So when i removed all the wrongly generated nether this was subtracted from their island level and now they have a level of about -500 to -3000.
I checked the database files but could not find the value that was created on island creation to zero out the island level so i was not able to reset anything. 

#### Steps to reproduce the behavior
Go to the nether world, place like a huge plane of diamond blocks. Then create an island and afterwards remove the diamond plane.

#### Expected behavior
I guess the island level should be zeroed by the blueprint and not by what actually was in the world? Or maybe have a setting to toggle this. In my world every island is supposed to be exactly the same so it would be totally fine to just subtract a static for every island.

##### Output of `/bbox version` (Mandatory)

```
[09:03:14 INFO]: Ausführen von PAPER 1.16.5.
[09:03:14 INFO]: BentoBox version: 1.16.2
[09:03:14 INFO]: Datenbank: JSON
[09:03:14 INFO]: Geladene Spielewelten:
[09:03:14 INFO]: skyblock_inseln (Inselwelt): Oberwelt, Nether, End
[09:03:14 INFO]: Geladene Addons:
[09:03:14 INFO]: Biomes 1.14.0 (ENABLED)
[09:03:14 INFO]: Border 3.1.1 (ENABLED)
[09:03:14 INFO]: BSkyBlock 1.14.4 (ENABLED)
[09:03:14 INFO]: ExtraMobs 1.11.0.3 (ENABLED)
[09:03:14 INFO]: Level 2.6.1 (ENABLED)
[09:03:14 INFO]: Limits 1.15.5 (ENABLED)
[09:03:14 INFO]: Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
AAC5, ArmorStandAdjustor, AsyncWorldEdit, BentoBox, bossascrew-bukkitutils, bossascrew-core-bukkit, bossascrew-core-libs, bossascrew-CustomDeathMessages*, bossascrew-oregenerator, bossascrew-navigator, bossascrew-skyblock, bossascrew-special-items, BungeeTabListPlus, ChestShop, ChestShopLogger, Citizens, ConditionalCommands, dtlTradersPlus, EntityDetection, Essentials, FarmControl, GSit, Harbor, HeadDatabase, HolographicDisplays, HolographicPlaceholders, ImageOnMap, LibsDisguises, LuckPerms, mcMMO, Multiverse-Core, MysqlEconomyBank, NBTAPI, PlaceholderAPI, PlayerParticles, PremiumVanish, ProtocolLib, Quests, Sentinel, ShulkerBoxBackPacks, SilkSpawners, spark, SurvivalInvisiframes, TAB, Vault, WorldBorderAPI, WorldEdit, WorldGuard, XConomy
```

**Comment by tastybento** [comment]
Hi,

There is an admin command `sethandicap` that enables you to change the island's initial value that gets deducted when a player requests the level. If you are in the console and do `island level (player name)` it will be shown in the report. I recommend you use this command instead of adjusting the database. You'll need to set it to something that mimics the value of a fresh island.

If you want or need to adjust the level database then you can find the data in IslandLevels table. In JSON, that is a folder in `plugins/BentoBox/database/IslandLevels`. Each island had its own record named by the unique island ID. Here's an example:

```
{
  "uniqueId": "BSkyBlockd37a98c5-4af7-49a9-9327-62c4841148cf",
  "level": 3,
  "initialLevel": 0,
  "pointsToNextLevel": 71,
  "uwCount": {},
  "mdCount": {
    "GRASS_BLOCK": 26,
    "OAK_LEAVES": 55,
    "POPPY": 1,
    "AIR": 2559842,
    "GRASS": 11,
    "OAK_LOG": 6,
    "BEDROCK": 1,
    "OAK_SIGN": 1,
    "DIRT": 55,
    "CHEST": 1,
    "DANDELION": 1
  }
}
```

The value to change is `initialLevel`. However, make sure the server is shutdown before manually editing database files.

I hope that helps. By the way, there is an admin setting (/bsb settings) that will automatically remove super-flat chunks. It'll alert you in the console log too so you can know where they were. If you still think some could be lurking, then set it to active.

**Comment by CubBossa** [comment]
Thank you very much!
