### ISSUE TITLE
Block values broken

### ISSUE THREAD

**Issue by Donutnut1** [BentoBoxWorld/Level#51]
When editing the island level config it doesn't actually do anything. The changes save and they aren't overwritten but the changes don't actually take effect on the server. For example if I change the levelwait value, the cooldown stays at the default value. This is the same for the levelcost also.

It also seems as if the island level is broken in general? Each cobblestone block placed counts as one level, rather than 1 point towards the 100 for a level as suggested by the default config.

**Comment by tastybento** [comment]
Thanks for the report, but we need the background info in the bug report template to know where to start. Most importantly, do /bbox version and copy and paste the result so we can see what versions of the plugin and add ons you are using.

**Description**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior:**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - OS: [e.g. iOS]
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**
Add any other context about the problem here.
