### ISSUE TITLE
Soft block limits

### ISSUE THREAD

**Issue by Minetown** [BentoBoxWorld/Level#60]
**Is your feature request related to a problem? Please describe.**
Instead of (or in addition to) a hard block limit, it would be nice to include a system where blocks above a certain level don't count for nothing, but instead count for less and less as more and more of the block is placed. This is similar to uSkyblock's diminishingreturns feature.

**Describe the solution you'd like**
Include an addition value to input in the level config for the value which the soft limit will kick in for each individual block. Then, in another part of the config, a place to set the scale at which the block values will diminish.

**Describe alternatives you've considered**
The ability to create other lists in the config to specify the worth of blocks when a number of them have been placed. For example, cobble being worth 1 per block after 10000 have been placed, .5 after 15000, etc.

**Comment by Poslovitch** [comment]
I've discussed of this idea as well with a French server owner.

# Demonstrating the idea using a classical probability density function
We came up with the idea of making the value of a block follow a very specific exponential function, which instead of increasing exponentially, **decreases increasingly slower**:
`value(x) = ke^(-kx)`, k>0.

## Some maths lessons
This density function comes from the probability field of maths.

It has a few interesting properties:
* the area below the curve is always equal to 1 (integrals).
* the ordinate of the point whose abscissa's 0 always equals `k`.
* all the values of this function are > 0.

## Demonstrating the behaviour of such function

### `k` ≈ 1
![image](https://user-images.githubusercontent.com/20014332/60000474-9c9de400-9664-11e9-8986-54a0eeb0604c.png)

### Greater value of `k`

The greater `k` is, the steeper the function decreases, which in my opinion is the behaviour we want: the more valuable is a block, the faster its value should go down.
![image](https://user-images.githubusercontent.com/20014332/60000610-d5d65400-9664-11e9-83dd-ff19a3434563.png)

### Small value of `k`
On the opposite, with a very small value, it decreases way slower:
![image](https://user-images.githubusercontent.com/20014332/60000821-48473400-9665-11e9-8f71-ee5b511e57d2.png)

# How to apply this to the block value calculation?

It obviously needs some tweaking. We don't want server owners to mess around with the formula itself, firstly because they may not understand it at all, secondly because it's not adapted to fit our use case.

## `k` = actual value of the block

### Definition

`k` mathematically being the very first value our function returns, it must therefore obviously be the actual value of the block. As such, `k` should follow the formula below:

![image](https://user-images.githubusercontent.com/20014332/60002620-441d1580-9669-11e9-9c3b-a2a25508f29c.png)

`v` and `p` are values that are already part of the configuration, so it's clearly going to be backward-compatible 😛.

### Examples

Along the whole explanation, I will use two examples : cobblestone and emerald block.

**`p = 100` (kind of default configuration)**

* **Cobblestone**: `v = 1`, therefore `k = 0.01`.
![image](https://user-images.githubusercontent.com/20014332/60002859-ce657980-9669-11e9-8d5c-73bc3ed82de2.png)

* **Emerald block**: `v = 100`, therefore `k = 1`.
Keeping the same scale on the x-axis therefore shows this result:
![image](https://user-images.githubusercontent.com/20014332/60002966-02d93580-966a-11e9-92b8-ba42b0af576f.png)

## `n` = number of blocks already placed

### Definition

`n` is mathematically the abscissa of all of the points of our density function.
In practice, this is the **numbers of blocks** that have already been placed, and `value(n)` is the value of the *n-th* block.

A hard limit of blocks can be implemented, yet, ideally, we want the value of the block to reach 0 once we reach this limit.

This leads us to this formula, with `l` (= *limit*) being the limit of the block:
![image](https://user-images.githubusercontent.com/20014332/60004006-12f21480-966c-11e9-8750-9506ce0cfec8.png)

### Examples

* **Cobblestone**: `l = Integer.MAX_VALUE` (because there are just no limit to it).
![image](https://user-images.githubusercontent.com/20014332/60004374-c824cc80-966c-11e9-8016-bc87a3a3fef1.png)

* **Emerald block**: `l = 1500`.
![image](https://user-images.githubusercontent.com/20014332/60004600-35386200-966d-11e9-9918-c7fda538a3a6.png)

You can see on the image above that the value of the block when we reach the limit is not equal to 0, but `0.37`.

## Fixing the limit?

Actually, it's mathematically impossible to ever reach a value of 0 because of one of the properties of the exponential function.

If we want the value to reach 0 at some point (the limit), we need to do the following:
![image](https://user-images.githubusercontent.com/20014332/60005221-5b123680-966e-11e9-86e0-ad10153f4938.png)

This fixes the limit... But `value(0)` will no longer be equal to `k`.
![image](https://user-images.githubusercontent.com/20014332/60005342-97de2d80-966e-11e9-8df3-abda2c5831dc.png)

## Calculating the actual island level

Up to now, we only calculated the **value** of a block corresponding to **how many blocks are already placed**. If we want to calculate the actual points it provides, we will need to use some integrals.

![image](https://user-images.githubusercontent.com/20014332/60005634-2baff980-966f-11e9-9c12-6eb70d8d8b80.png)

And just because this is funny to write things down in LaTeX:
![image](https://user-images.githubusercontent.com/20014332/60005975-daecd080-966f-11e9-845e-25909960e5f6.png)

**Comment by Poslovitch** [comment]
I'm discussing of this idea with an old Skyblock player. He'd like that the value command should specify

**Comment by Poslovitch** [comment]
I discussed of this idea again with an experience Skyblock player. He raised a few concerns:
- it should be clarified in the value command that points are decreasing the more blocks you place down;
- the original value of the block **and** the value of the *n-th* block should also be precised;
- this might piss off the big players as the more levels they have, the slower they will achieve further progression.

**Comment by BONNe** [comment]
I like this idea... but dynamic it will be hard to explain to players how much each block would cost.

one solution would be to create a ladder system when you could specify in config each step size (or dynamic) but all blocks in this step should be the same value.

That could fix or simplify the first two problems.

The last issue... it is not an issue. If they had so large island, there is no problem to create it bigger :)

**Comment by tastybento** [comment]
Simple is good. The current system is simple. As someone who has to handle support requests from admins who don't understand the current system (usually once I point them to the console report, they start to understand), I'd prefer not to increase the support load. Anyway, if there's a PR to do it, I'd look at it.

**Comment by plagoutte** [comment]
> 
> 
> Simple is good. The current system is simple. As someone who has to handle support requests from admins who don't understand the current system (usually once I point them to the console report, they start to understand), I'd prefer not to increase the support load. Anyway, if there's a PR to do it, I'd look at it.

Current system is simple, this is the point. By rewarding players who just farm a lot, buy diamond blocks and place it, we encourage players to stay AFK on their island and wait for the resources to come, to climb to the top of the ranking. 

On the other hand, the system imagined by @Poslovitch would force players to diversify blocks on their island, by **building** and island, not just amass a huge quantity of ugly diamond blocks. So, players are more interactive (with other players, by trading rare blocks for example).

Also, I suggest `k` decreases when the total number of blocks on the island increases (to prevent experimented players to be blocked at a certain stage of the game).

**Comment by tastybento** [comment]
I believe this was implemented as a result of the equation-style level calculation. So, blocks can be worth less as levels rise. Closing.
