### ISSUE TITLE
PAPER 1.14.4 - level causes serious TPS loss sometimes

### ISSUE THREAD

**Issue by KarlPro123** [BentoBoxWorld/Level#68]
Here’s the picture:  

https://media.discordapp.net/attachments/310623455462686720/602892726400319602/f51a4775a7682d90a58fea8851a53eab.png

I don’t think even players should be playing for this to happen as it happens when I am developing my Skyblock servers.
Note that I am using BentoBox 1.5.3 and Level version 1.5.0. Server laggs for 10 seconds and TPS drops from 20 to 16.

**Comment by tastybento** [comment]
What is your BSkyBlock confit file? How big is the protection size?

**Comment by KarlPro123** [comment]
https://pastebin.com/ddH2av1D

**Comment by tastybento** [comment]
Does this always happen? Or just randomly?

These are just notes:

The [crash report](https://media.discordapp.net/attachments/310623455462686720/602892726400319602/f51a4775a7682d90a58fea8851a53eab.png) is caused by a new island being created so someone must have been playing and created a new island for this crash.

The crash occurred because it took more than 10 seconds to grab the chunk coords for this island but the island size is normal. Maybe some kind of world loading glitch. 10s is very long time. Code can be re-written to remove need to get a block at each chunk. That may help but isn't a root cause fix.

Hmmm..

**Comment by tastybento** [comment]
Okay, this should help. Let me know if the latest build has any issues.
