### ISSUE TITLE
Support for WildStacker

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Level#87]
**Is your feature request related to a problem? Please describe.**
With aSkyBlock there is support for WildStacker, basically when stacking blocks into a single block the level should go up as if the blocks were physically placed and when the stack is broken the levels should go down as if each block were broken.

**Describe the solution you'd like**
Support for WildStacker block stacking.

**Describe alternatives you've considered**
aSkyBlock

**Additional context**
If you have any questions you can get me on discord, here is my ID: Tina King#7369

This is a link to WildStacker on Spigot:
https://www.spigotmc.org/resources/%E2%AD%90%EF%B8%8F-wildstacker-%E2%AD%90%EF%B8%8F-stack-mobs-items-blocks-spawners-with-hopper-support.60648/

**Comment by Poslovitch** [comment]
ASkyBlock does not support WildStacker. It's the developer of this plugin who provided some sort of integration as far as I'm aware. It's been suggested on BentoBox's repo we add a Hook for WildStacker, thus allowing addons to integrate with it. However, since this plugin is not the only own of its kind and is a premium resource, this might never happen. 

This is WildStacker's developer's job to implement its integration the same way he did on ASB. If he finds himself lacking the API to do so, he can suggest changes. 🙂

**Comment by OmerBenGera** [comment]
You can add support by using the public API that is available.
Therefore, it's not possible to WildStacker to add support to your plugin. Every plugin that wanted to support WildStacker, added their own support.

**Comment by OmerBenGera** [comment]
@Poslovitch

**Comment by tastybento** [comment]
No need to tag.

We'll look into it. If there's a developer who wants to contribute a PR to enable this, it'd be welcome.
