### ISSUE TITLE
[FEATURE REQUEST] The ability to exclude certain members from /is top

### ISSUE THREAD

**Issue by MrPranklez** [BentoBoxWorld/Level#88]
#### Is your feature request related to a problem?
I would like to exclude my staff from /is top. I've tried to assigning the following permission: "-bskyblock.intopten", but sadly it still occurs that a staff member gets put into /is top, despite the negation.

#### Describe the solution you'd like us to implement.
So I guess what I'm suggesting is the addition of a permission like: "bskyblock.excludetopten", to permanently keep someone out of is top.

**Comment by tastybento** [comment]
I'm not sure this is a valid feature request because the feature already exists. Only players who have the permission **bskyblock.intopten** are put in the top ten. This check is done with the Bukkit permission check, so if your staff are being included, they must have that permission somehow (maybe bskyblock.*?) Either way, enabling another permission isn't going to fix the root cause and will just cause more confusion. I suggest you try to fix the permission issue.
